acceleratorFor.MindMap/NewMapViewAction=F1
acceleratorFor.MindMap/EditAction=F2

acceleratorFor.MindMap/FoldOneLevelAction=F3
acceleratorFor.MindMap/UnfoldOneLevelAction=F4

acceleratorFor.MindMap/New_on_selected_node=F5
acceleratorFor.MindMap/Edit_on_selected_node=F6
acceleratorFor.MindMap/UpdateNextSteps_on_selected_node=F7
acceleratorFor.MindMap/AddToToDo_on_selected_node=F8

acceleratorFor.MindMap/Filter_on_selected_node=F9
acceleratorFor.MindMap/SearchWithInazumaSearch_on_selected_node=F10

acceleratorFor.MindMap/Rename_on_selected_node=F11
acceleratorFor.MindMap/Delete_on_selected_node=F12
