acceleratorFor.MindMap/NewMapView_on_single_node=F1
acceleratorFor.MindMap/Edit_on_single_node=F2

acceleratorFor.MindMap/FoldOneLevel_on_single_node=F3
acceleratorFor.MindMap/UnfoldOneLevel_on_single_node=F4

acceleratorFor.MindMap/Filter_on_selected_node=F5
acceleratorFor.MindMap/SearchWithInazumaSearch_on_selected_node=F6
acceleratorFor.MindMap/AddToToDo_on_selected_node=F7
acceleratorFor.MindMap/UpdateNextSteps_on_selected_node=F8

acceleratorFor.MindMap/NewPage_on_selected_node=F9
acceleratorFor.MindMap/NewDirectory_on_selected_node=F10
acceleratorFor.MindMap/Rename_on_selected_node=F11
acceleratorFor.MindMap/Delete_on_selected_node=F12
