FROM mcr.microsoft.com/devcontainers/universal:6-linux

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bubblewrap \
        build-essential \
        file \
        sed \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
